-- SQL for testing standards

CREATE TABLE MY_REALLY_LONG_TABLE_NAME_THAT_EXCEEDS_LIMIT_FILE (
    ID NUMBER,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    CONSTRAINT MYPK PRIMARY KEY (ID)
);

CREATE TABLE VALID_USERS (
    USER_ID NUMBER,
    USERNAME VARCHAR2(30),
    ENT_DTM DATE,
    ENT_USER_ID VARCHAR2(30),
    UPD_DTM DATE,
    UPD_USER_ID VARCHAR2(30),
    CONSTRAINT VALID_USERS_PK PRIMARY KEY (USER_ID)
);

CREATE VIEW BROKEN_VIEW AS 
SELECT * FROM VALID_USERS;

CREATE OR REPLACE VIEW VALID_USERS_VW AS
SELECT * FROM VALID_USERS;

ALTER TABLE VALID_USERS ADD CONSTRAINT BAD_FK FOREIGN KEY (USERNAME) REFERENCES OTHER_TABLE (USERNAME);
ALTER TABLE VALID_USERS ADD CONSTRAINT VALID_USERS_FK1 FOREIGN KEY (USER_ID) REFERENCES OTHER_TABLE (ID);

